### ISSUE TITLE
Plotting issue with US state of Georgia in linear scale

### ISSUE THREAD

**Issue by jpeisen1963** [aatishb/covidtrends#116]
For some reason April 12th comes at the same time, or slightly before, April 11th on [this graph](https://aatishb.com/covidtrends/?scale=linear&region=US&location=Georgia).  Logarithmic scale seems fine.

I'm using a Pixelbook Go running Chrome version 81.0.4044.94 in case it is just my rendering...

**Comment by aatishb** [comment]
Thanks for pointing this out! It looks like this is a [known issue](https://github.com/nytimes/covid-19-data/issues/203) with the NYT data, documented [here]( https://github.com/nytimes/covid-19-data/blob/master/README.md#geographic-exceptions).

Since this isn't a problem on our end, perhaps we should close this?

**Comment by jpeisen1963** [comment]
The known issue for GA appears to be the decline in cases - see the lines below.  That doesn't really explain why the graph folded back on itself -- the horizontal placement of April 12th should still be between the 11th and 13th, but it isn't.

date | state | fips | cases | deaths
--- | --- | --- | --- | ---
... | | | |
2020-04-11 | Georgia | 13 | 12261 | 432
... | | | |
2020-04-12 | Georgia | 13 | 12103 | 438

**Comment by aatishb** [comment]
Hi, I'm attaching a screenshot just to make sure we're discussing the same thing. Is this the kink in the graph you are referring to?

![Covid Trends(7)](https://user-images.githubusercontent.com/1878638/80017488-ab327300-84a2-11ea-85fb-2da80eabb0c7.png)

From what I can tell, this is the correct behavior. As you point out, from April 11 -> 12, the total number of cases went down in the NYT dataset from 12,261 to 12,103. This also caused a further drop in the number of weekly cases. Since the x axis is the number of cases and the y axis is the number of weekly cases, the graph moved down and to the left for that day.

Perhaps I'm misunderstanding the issue?

**Comment by meli-lewis** [comment]
Hey y'all, Albert Sun responded to my issue [here](https://github.com/nytimes/covid-19-data/issues/203#issuecomment-617892967)! Regarding Georgia specifically, he said: 

> GA — the state started breaking out cases from their Unknown category for cases in "Non-Georgia Residents". We started excluding those from the statewide total to match how other states are reporting cases.

**Comment by jpeisen1963** [comment]
I'm sorry - yes you were absolutely right.  Sometimes I have issues wrapping my brain around "horizontal is not time"..
