### ISSUE TITLE
Auto-update custom URL

### ISSUE THREAD

**Issue by aatishb** [aatishb/covidtrends#163]
Currently users have to click the _Create Shareable Link_ button to create a custom link to their modified graph. I see two issues with this:

1. People many not know this button creates a custom link, and might assume it's a typical social share button. So some folks are sharing the default graph with comments like 'you have to select Norway' etc.
2. If I remember correctly, the placement of this button was the reason we don't have a scroll bar for the entire aside section, which is now leading to an issue with browser zooming (described in #148). A couple of people have also written to me about that issue.

So I suggest:
1. We auto-update the custom URL on UI changes. We check to ensure the selected settings are different from the default, so that we retain a simple URL if the graph has not been customized
2. We remove the Create Shareable Link button
3. Instead of scrolling within the Countries list, we make the entire aside section scrollable.

This will resolve #148 and make sharing of custom graphs easier.

Thoughts? I welcome any feedback on this idea.

**Comment by MrSpiffyClean** [comment]
I was looking at the CSS code on the live page (to see if I could do anything regarding the countries not appearing) and it appears that the aside section is already scrollable. The issue is that, since the countries section is also scrollable, the browser is shrinking the countries to a minimum size (in order to fit everything else that was added) such that the aside section can fit the window. Removing `overflow-y` from `.countries` solves this. I'm guessing setting heights to the other elements is an option, but that makes stuff look worse.

While I have never used the Create Shareable Link button, I do ask why it is at the bottom of the aside section, and not, say, at the middle. I was writing something about needing to scroll the countries' list in order to actually see the button, but I misremembered and the button was always visible.
Also, there isn't a lot of output that the button did anything. It does say that it copied to the clipboard for a couple of seconds, but that's it. Maybe a window with share options (like how Youtube has) could solve this, but it is added effort for something people apparently aren't using.

Since clicking the Create Shareable Link button already changes the URL, it doesn't seem that much harder to just have it update every time a country is selected or deselected.

**Comment by rpkoller** [comment]
I would agree 100% to the first two suggestion @aatishb on number three i am still uncertain what the best way to solve it would be. the list is looooong for world wide. and i know the issue on small viewport heights but due to the long countries list the customizations on top to have at hand more easily has also some advantage. overall not entirely sure about suggestion three the first two complete agreement

**Comment by aatishb** [comment]
@mrspiffyclean thanks for this analysis.

@rpkoller Fair point. When building this, I was taking inspiration from [Google Public Data Explorer](https://www.google.com/publicdata/explore?ds=d5bncppjof8f9_&ctype=b&strail=false&nselm=s&met_x=sp_dyn_le00_in&scale_x=lin&ind_x=false&met_y=sp_dyn_tfrt_in&scale_y=lin&ind_y=false&met_s=sp_pop_totl&scale_s=lin&ind_s=false&dimp_c=country:region&ifdim=country&iconSize=0.5&uniSize=0.035) to scroll the country list the way I did.

I think I see your point that making the whole aside scrollable is not ideal. Perhaps instead we have collapsible sections like they do in public data explorer, have each section be scrollable, and ensure that both Countries and Customize take up no more than half the height of the aside section.

Let's separate these issues, so we have CSS improvements as a separate issue, and remove 'create shareable link' button for this one?

**Comment by rpkoller** [comment]
yep i agree those are two separate issues. the removal part should be quickly solved and would be simply stalled by the more tricky usability issue. so yep two separate issues would be best.

and the halving idea sounds interesting. only problem i see in that regard is if you wanna go mobile first and responsive how that idea works on lets say an iphone se screen. ;) or maybe wit a media query we might provide slighty differing behaviors. on a desktop viewport with enough viewport height provide the halving with too less of a viewport height provide toggles?

**Comment by MrSpiffyClean** [comment]
Just a small sidenote I forgot to add before. While I think there is value in having a country list, I have almost exclusively used the search/filter input box to select countries, as being on a desktop, I find it easier to just type the first 3 or 4 characters of a given country's name rather than scrolling the admittedly large list.
The list helps in that it shows everything, such that countries with multiple common names (such the US - USA - United States...) are easier to find there.

I also think they are separate issues, the CSS stuff being the trickiest to solve, as it amounts to usability issues, which are wide ranging and don't affect everyone the same way.

**Comment by rpkoller** [comment]
@MrSpiffyClean i consider the scrollable list of countries on the desktop too long as well. i usually also take the approach to use the search bar to narrow down the selection ;)))

**Comment by aatishb** [comment]
Closing as this is now live. Let's open a separate issue for cleaning up the side navigation bar i.e. CSS improvements to zoom & scroll behavior.
