### ISSUE TITLE
Add Lighthouse Audit

### ISSUE THREAD

**Issue by aatishb** [aatishb/covidtrends#170]
With #136 we got our accessibility score up to 100. While this is just a first step towards enhancing the accessibility of our website, it might be nice to automatically keep track of this score with updates, so we are aware of any potential areas of concern.

I noticed there's a GitHub Action for this: https://github.com/marketplace/actions/lighthouse-audit

> the action will print the five scores (out of 100) to the output and upload HTML and JSON versions of the report as artifacts

It seems like this might be nice to incorporate.

**Comment by rpkoller** [comment]
good idea! microsoft is also working on accessibility insights: https://github.com/microsoft/accessibility-insights-action but it isnt production ready yet and i dont know the extra benefits that might be incorporated. for automated tests both rely on axe-core/Axe-coconut would be interesting which tests each turns on and off. but in any case a good way to take care that no basic no no's slip in in future commits by accident for covidtrends.

**Comment by aatishb** [comment]
Thanks for the feedback @rpkoller!

To be honest I'm a bit out of my depth with this as I've new to using Github Actions. Ideally, it would be great if we could audit any PRs *before* they are merged, so that we can correct any issues before they go live. It's not clear to me how to set this up. 

Also, there are also some other implementations of this listed [here](https://github.com/marketplace?type=actions&query=lighthouse), in case any of the others are easier to set up for our purposes.

**Comment by rpkoller** [comment]
hmmm your workflows yaml file says: 

```
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```

when a commit is pushed into `master` the jobs listed afterwards are being triggered. if you push a commit into the branch `test` the jobs wont run. same goes for the pull requests. every pull request against `master` should trigger the jobs. if i create branch `newfeature` on my fork of covidtrends and place a pulll request to the branch `newfeature` it wont be checked either. If you leave out the branches part for pull request ( something i found at jeff geerlings repo in the documentary i havent)

```
on:
  push:
    branches: [ master ]
  pull_request:
```
the jobs run for pushes to master and for all pull_requests to the whole repo no matter which branch they are in. an useful addition might also be: 

```
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 6 * * 0'
```
so the jobs are ran once per week anyway no matter a commit was placed or not. might be of interest especially for the performance aspect. 

two nitpicks i picked up from jeff geerling in regards of yaml files in general. they should start with `---` in the first line. then you normally have a key, a colon and a value so he puts `on` normally within quotes because it is a string ( https://youtu.be/dE7IksPs9EY?t=917 ). if you dont do that that yaml actually identifies it as a boolean value (on, yes, true).

```
---
name: CI
'on':
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 6 * * 0'
```

and about the performance tests. the first you choose looks fine. https://github.com/marketplace/actions/lighthouse-audit Paul Jarvis rings a bell. meaning it is a familiar name, savvy,  and the stars and number of contributors look decent. but taken a quick look at the others listed in your second link that one sticks out: https://github.com/marketplace/actions/lighthouse-ci-action paul irish and a few other googlers on the contributors list. and they are at version `2.x` while the other is version `.3`. 

but testing the performance you have to keep one thing in mind basically testing for "performance" makes only sense on the production server. otherwise you have environmental differences. and just testing for applied patterns is half baked ;)  but looks you are able to test several websites. so you might name the repo on github as well as https://aatishb.com/covidtrends/ ... then you could see if the production version is steady and behaving well while checking the impact on the github version for the changes before they a merged.
